# //R 7
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 759197960365-tsddb8imb66pohm3taqltrhj0q68hk32.apps.googleusercontent.com
            client-secret: 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
            #scope: profile, email
            #redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            #authorization-grant-type: authorization_code
            #client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
